"use client";

import { Poppins } from "next/font/google";
import "./globals.css";

import { usePathname } from "next/navigation";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/Navbar";
// import type { Metadata } from "next";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "400", "600", "800"],
});

// export const metadata: Metadata = {
//   title: "NextJS",
//   description: "Generated by create next app",
// };

const DisabledNavbar = ["/login", "/register"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={poppins.className}>
        <SessionProvider>
          {DisabledNavbar.includes(pathname) ? null : <Navbar />}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
